spring:
 profiles:
  active: pre
---  
spring:
 profiles: dev
zk:
 hosts: 10.0.31.133:2181
---
spring:
 profiles: pre
zk:
 hosts: 106.14.217.42:2181
---
spring:
 profiles: pro
zk:
 hosts: 172.19.101.243:2181