spring:
 profiles:
  active: dev
---  
spring:
 profiles: dev
zk:
 hosts: 49.234.99.59:2181
---
spring:
 profiles: pre
zk:
 hosts: 49.234.99.59:2181
---
spring:
 profiles: pro
zk:
 hosts: 49.234.99.59:2181